### ISSUE TITLE
How to get SILVA132-typestrains.arb ?

### ISSUE THREAD

**Issue by jgrzadziel** [KasperSkytte/AutoTax#3]
Maybe the solution is obvious but I cannot find the SILVA132-typestrains.arb file in any location. 
I found only SILVA_132_SSURef_NR99_13_12_17_opt.arb.

Is this file available to download or I need to create one ?

Best regards

**Comment by KasperSkytte** [comment]
Hi there

You will have to make one yourself through ARB by downloading the SILVA database. But maybe we can post it somewhere online to download, it's quite large.

**Comment by KasperSkytte** [comment]
Oh, it's already on the SILVA website, so no need :) https://www.arb-silva.de/download/arb-files/

**Comment by KasperSkytte** [comment]
And extracting the typestrains database from ARB is described here: https://www.biorxiv.org/content/10.1101/672873v1.supplementary-material?versioned=true

**Comment by jgrzadziel** [comment]
@KasperSkytte Thank you a lot !

**Comment by KasperSkytte** [comment]
I uploaded the 4 files here https://doi.org/10.6084/m9.figshare.9994568
