### ISSUE TITLE
Missing content of example_data/10k_fSSUs.fa

### ISSUE THREAD

**Issue by aaronsaunders** [KasperSkytte/AutoTax#5]
The file `example_data/10k_fSSUs.fa` is empty. 

Looks like you may have deleted its contents in commit 8418b859abc78c46d05b2c16c3364c5d174dd12a ?

**Comment by KasperSkytte** [comment]
Hi Aaron!

Thank you for notifying. I will fix it when I get time during/after paternity leave (until late March). But maybe you can get it from a previous commit? Haven't tested, writing from the phone. Or else @msdueholm can provide you a subset or full set of MiDAS3 sequences

**Comment by aaronsaunders** [comment]
No problem. I got it as you say from the previous commit. Just letting you know. 
Anyway, enjoy fatherhood. They are experiences you will treasure!

**Comment by KasperSkytte** [comment]
Fixed in https://github.com/KasperSkytte/AutoTax/commit/d4521a6bb336a5e77556d250e60106abf21937b5
