### ISSUE TITLE
bug in script autotax.sh

### ISSUE THREAD

**Issue by oschakoory** [KasperSkytte/AutoTax#8]
Hi, first of all, thank you for this tool. It seems to be very interesting and it is exactly what i need for my study.

I first ran getsilvadb.sh to create my database (file.arb, file.udh, file_typestrains.udh).
Everything ran well until i run autotax.bash with my fasta file:

bash autotax.bash -i file.fasta
[2021-06-28 11:57:15]: Checking for required R packages and installing if missing...
[2021-06-28 11:57:17]:   - Orienting sequences...
[2021-06-28 11:57:19]:   - Dereplicating sequences...
[2021-06-28 11:57:19]:   - Denoising sequences using UNOISE3
usearch v11.0.667_i86linux32, 4.0Gb RAM (16.0Gb total), 8 cores
(C) Copyright 2013-18 Robert C. Edgar, all rights reserved.
https://drive5.com/usearch

License: personal use only

00:00 41Mb    100.0% Reading temp/uniques_wsize.fa
[2021-06-28 11:57:19]:   - Finding the longest representative sequence of identical sequences, then reorder and rename...
Error in S4Vectors:::normarg_names(value, class(x), length(x)) : 
  attempt to set too many names (2) on GroupedIRanges object of length 0
Calls: names<- -> names<- -> names<- -> names<- -> <Anonymous>
Exécution arrêtée

Can you tell me where i went wrong? I double checked everything but it is still not working.

Thank you for your help.

**Comment by KasperSkytte** [comment]
Hi there. Check the `uniques_wsize.fa` file, it's likely empty judging by how quickly it reached that step. How many sequences are you trying to process? Are they already dereplicated?

**Comment by oschakoory** [comment]
In the uniques_wsize.fa, there is 55 sequences just like in my input file. My input file was already dereplicated (at 100%) and clustered at 97% before using autotax.

**Comment by KasperSkytte** [comment]
Okay. That's tiny. But the denoise step is filtering everything not present at least twice, see https://github.com/kasperskytte/autotax#what-the-script-does. So you will get 0 output from that step. So you have to adjust that setting, either edit the script, or run a `export denoise_minsize=1` before starting.

**Comment by oschakoory** [comment]
I have edited the script and it is now running without error. Thank you so much for such a rapid and efficient reply.

**Comment by KasperSkytte** [comment]
You're welcome. I have just updated the readme to describe the few settings more clearly.
